### PR TITLE
Trying to fix shit

### PR DESCRIPTION
**Pull request by design1online**
* Adds a better log
* Adds log messages
* Fixes rendering ticks
* Fixes player not showing up
* Fixes some messed up event listeners from auto-binding

### CODE REVIEW

**Comment by Veradictus** [comment]
Shoot me a message on Discord if you need some help Failure#7243

**Comment by design1online** [comment]
> Shoot me a message on Discord if you need some help Failure#7243

@Veradictus how do I do that?

**Comment by Veradictus** [comment]
@design1online https://discordapp.com/

**Comment by design1online** [comment]
@Veradictus it says I need your tag number. Mine is Design1online#5678

**Comment by Veradictus** [comment]
@design1online Sent a friend request.

**Pull request merged**
